// Generated by CoffeeScript 1.6.3
(function() {
  var calculateButton, calculateISBN13, getDigits, getMultipliedArray;

  getDigits = function(value) {
    var digits, lastDigit;
    digits = [];
    while (value > 0) {
      lastDigit = value % 10;
      digits.splice(0, 0, lastDigit);
      value = parseInt(value / 10);
    }
    return digits;
  };

  getMultipliedArray = function(digits) {
    var digit, multipliedArray, multiplyWithThree, val, _i, _len;
    multipliedArray = [];
    multiplyWithThree = false;
    for (_i = 0, _len = digits.length; _i < _len; _i++) {
      digit = digits[_i];
      val = digit;
      if (multiplyWithThree) {
        val *= 3;
      }
      multipliedArray.push(val);
      multiplyWithThree = !multiplyWithThree;
    }
    return multipliedArray;
  };

  calculateISBN13 = function(value) {
    var digits, isbn13, lastDigit, mod10, multipliedArray, sumOfMultipled;
    digits = getDigits(value);
    multipliedArray = getMultipliedArray(digits);
    sumOfMultipled = multipliedArray.reduce(function(a, b) {
      return a + b;
    });
    mod10 = sumOfMultipled % 10;
    lastDigit = 10 - mod10;
    isbn13 = value * 10 + lastDigit;
    return alert(isbn13);
  };

  calculateButton = document.getElementById("calculate");

  calculateButton.onclick = function() {
    var isbn12, isbn12Input;
    isbn12Input = document.getElementById("isbn12");
    isbn12 = parseInt(isbn12Input.value);
    if (isNaN(isbn12)) {
      return alert("Please enter a valid number");
    } else {
      return calculateISBN13(isbn12);
    }
  };

}).call(this);
